// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Counter$YourProjectName from "./Counter.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Counter$YourProjectName.make, {
          name: "Reason React"
        }), "index1");

export {
  
}
/*  Not a pure module */
